name: Package

on:
  release:
    types: [ created ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package
        id: package
        run: git archive HEAD --format=zip --worktree-attributes --prefix="TrinketMenu/" -o "TrinketMenu-${{ github.event.release.tag_name }}.zip"

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: TrinketMenu-${{ github.event.release.tag_name }}.zip
          asset_path: ./TrinketMenu-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
